# Basic Info
title: Mohan Kumar
tagline:          "Yet another developer\'s blog"
description:      "My Technical diary and blog"
url: "https://mohanarunachalam.github.io/"
baseurl: /

# description: Mohan Kumar's website

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

plugins:          [jekyll-paginate]
paginate:         5

collections:
  about:
    output: true
    permalink: /:collection/:path

  courses:
    output: true
    permalink: /:collection/:path

  posts:
    output: true
    permalink: /:collection/:path

  

author:
  name:           "Mohan Kumar"
  url:            "https://mohanarunachalam.github.io"


# remote_theme: ankitsultana/researcher@gem

# gems:
# - jekyll-redirect-from

# include: ["_pages"]

# github_username:      mohanarunachalam
# linkedin_username:    mohan-kumar-11824877
# quora_username:       Mohan-Kumar-243
# facebook_username:    mohankumar011
# twitter_username:     MohanKumar10011

social:
  github:        "https://github.com/mohanarunachalam"
  # blog:          "https://github.com/ThibaultLaurens/thibaultlaurens.github.io"
  linkedin:      "https://www.linkedin.com/in/mohan-kumar-11824877"
  # quora: 
theme: jekyll-theme-cayman